# Generated by Django 5.2.6 on 2025-10-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='account',
            new_name='user',
        ),
    ]
